"""Project template registry and scaffolding."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Template:
    key: str
    name: str
    description: str
    files: dict  # relative path -> template string with {name} placeholder


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9_-]+", "-", name.lower()).strip("-") or "project"


TEMPLATES: dict[str, Template] = {
    "fastapi": Template(
        "fastapi",
        "FastAPI service",
        "Minimal async API with health endpoint.",
        {
            "README.md": "# {name}\n\nFastAPI starter generated by Loadout.\n\n```bash\npip install -r requirements.txt\nuvicorn main:app --reload\n```\n",
            "requirements.txt": "fastapi>=0.110\nuvicorn[standard]>=0.27\n",
            "main.py": (
                '"""FastAPI starter — {name}"""\n\n'
                "from fastapi import FastAPI\n\n"
                'app = FastAPI(title="{name}")\n\n\n'
                '@app.get("/health")\n'
                "def health():\n"
                '    return {{"status": "ok", "service": "{name}"}}\n'
            ),
        },
    ),
    "nextjs": Template(
        "nextjs",
        "Next.js app",
        "Minimal Next.js 14 app router starter (package.json + page).",
        {
            "README.md": "# {name}\n\nNext.js starter. Run: `npm install && npm run dev`\n",
            "package.json": (
                '{{\n  "name": "{slug}",\n  "private": true,\n'
                '  "scripts": {{\n    "dev": "next dev",\n'
                '    "build": "next build",\n    "start": "next start"\n  }},\n'
                '  "dependencies": {{\n    "next": "^14.0.0",\n'
                '    "react": "^18.2.0",\n    "react-dom": "^18.2.0"\n  }}\n}}\n'
            ),
            "app/page.tsx": (
                "export default function Home() {{\n"
                "  return (\n"
                "    <main>\n"
                "      <h1>{name}</h1>\n"
                "      <p>Next.js starter from Loadout.</p>\n"
                "    </main>\n"
                "  );\n"
                "}\n"
            ),
        },
    ),
    "python-agent": Template(
        "python-agent",
        "Python AI agent",
        "Minimal tool-calling agent stub (stdlib + instructions).",
        {
            "README.md": "# {name}\n\nPython agent starter. Add your LLM client of choice.\n",
            "requirements.txt": "# openai>=1.0  # optional\n",
            "agent.py": (
                '"""Agent stub — {name}"""\n\n'
                "def run(prompt: str) -> str:\n"
                '    """Replace with your model call (Ollama, OpenAI, ...)."""\n'
                '    return f"Echo: {{prompt}}"\n\n\n'
                'if __name__ == "__main__":\n'
                '    print(run("Hello from Loadout"))\n'
            ),
        },
    ),
    "rag": Template(
        "rag",
        "RAG starter",
        "Document ingest + query stub (no vector DB — extension point).",
        {
            "README.md": ("# {name}\n\nRAG starter. Plug in Chroma, LanceDB, or pgvector.\n"),
            "requirements.txt": "# chromadb>=0.4  # optional\n",
            "rag.py": (
                '"""RAG stub — {name}"""\n\n'
                "DOCS: list[str] = []\n\n\n"
                "def ingest(text: str) -> None:\n"
                "    DOCS.append(text)\n\n\n"
                "def query(question: str) -> str:\n"
                '    return DOCS[0] if DOCS else "No documents ingested yet."\n'
            ),
        },
    ),
    "mcp-server": Template(
        "mcp-server",
        "MCP server",
        "Minimal MCP server package stub (Python entry + README).",
        {
            "README.md": ("# {name}\n\nMCP server starter. See modelcontextprotocol.io for SDK.\n"),
            "pyproject.toml": (
                '[project]\nname = "{slug}"\nversion = "0.1.0"\n'
                'requires-python = ">=3.9"\n'
                'description = "MCP server starter"\n\n'
                '[project.scripts]\n{slug}-mcp = "server:main"\n'
            ),
            "server.py": (
                '"""MCP server stub — {name}"""\n\n'
                "def main() -> None:\n"
                '    print("Implement MCP server protocol here.")\n\n\n'
                'if __name__ == "__main__":\n'
                "    main()\n"
            ),
        },
    ),
}


def list_templates() -> list[dict]:
    return [
        {"key": t.key, "name": t.name, "description": t.description, "files": len(t.files)}
        for t in TEMPLATES.values()
    ]


def preview_template(key: str, name: str) -> dict:
    tpl = TEMPLATES.get(key)
    if tpl is None:
        return {"ok": False, "reason": f"unknown template: {key}"}
    slug = _slug(name)
    files = []
    for rel in sorted(tpl.files):
        files.append({"path": rel, "bytes": len(tpl.files[rel].format(name=name, slug=slug))})
    return {
        "ok": True,
        "key": key,
        "name": name,
        "slug": slug,
        "files": files,
        "file_count": len(files),
    }


def scaffold_template(
    key: str,
    name: str,
    target_dir: str | Path,
    *,
    force: bool = False,
) -> dict:
    tpl = TEMPLATES.get(key)
    if tpl is None:
        return {"ok": False, "reason": f"unknown template: {key}"}

    root = Path(target_dir)
    slug = _slug(name)
    ctx = {"name": name, "slug": slug}

    if root.exists() and any(root.iterdir()) and not force:
        return {
            "ok": False,
            "reason": "target not empty — pass force=True to overwrite",
            "target": str(root),
        }

    written: list[str] = []
    skipped: list[str] = []

    for rel, content_tpl in tpl.files.items():
        dest = root / rel
        if dest.exists() and not force:
            skipped.append(str(dest))
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content_tpl.format(**ctx), encoding="utf-8")
        written.append(str(dest))

    if skipped and not force:
        return {
            "ok": False,
            "reason": "target not empty — pass force=True to overwrite",
            "skipped": skipped,
            "written": written,
        }

    return {
        "ok": True,
        "key": key,
        "target": str(root),
        "written": written,
        "file_count": len(written),
    }
